# Generated by Django 5.2.7 on 2026-04-19 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0002_notamateria'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notamateria',
            options={'ordering': ['epoca', 'materia'], 'verbose_name': 'Nota por Matéria', 'verbose_name_plural': 'Notas por Matéria'},
        ),
    ]
