import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0003_questao_dificuldade'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        CREATE TABLE IF NOT EXISTS "escola_perfilturma" (
                            "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                            "papel" varchar(10) NOT NULL,
                            "aluno_id" integer NOT NULL UNIQUE,
                            "turma_id" bigint NOT NULL,
                            CONSTRAINT "escola_perfilturma_aluno_id_fk" FOREIGN KEY ("aluno_id") REFERENCES "escola_aluno" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
                            CONSTRAINT "escola_perfilturma_turma_id_fk" FOREIGN KEY ("turma_id") REFERENCES "escola_turma" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
                        );
                        CREATE UNIQUE INDEX IF NOT EXISTS "escola_perfilturma_turma_papel"
                            ON "escola_perfilturma" ("turma_id", "papel");
                    """,
                    reverse_sql='DROP TABLE IF EXISTS "escola_perfilturma"',
                ),
                migrations.RunSQL(
                    sql="""
                        CREATE TABLE IF NOT EXISTS "escola_registroassiduidade" (
                            "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                            "data" date NOT NULL,
                            "observacao" text NOT NULL,
                            "registrado_por_id" integer NOT NULL,
                            "turma_id" bigint NOT NULL,
                            CONSTRAINT "escola_registroassiduidade_registrado_por_id_fk" FOREIGN KEY ("registrado_por_id") REFERENCES "escola_aluno" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
                            CONSTRAINT "escola_registroassiduidade_turma_id_fk" FOREIGN KEY ("turma_id") REFERENCES "escola_turma" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
                        );
                    """,
                    reverse_sql='DROP TABLE IF EXISTS "escola_registroassiduidade"',
                ),
                migrations.RunSQL(
                    sql="""
                        CREATE TABLE IF NOT EXISTS "escola_presencaaluno" (
                            "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                            "presente" boolean NOT NULL,
                            "aluno_id" integer NOT NULL,
                            "registro_id" bigint NOT NULL,
                            CONSTRAINT "escola_presencaaluno_aluno_id_fk" FOREIGN KEY ("aluno_id") REFERENCES "escola_aluno" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
                            CONSTRAINT "escola_presencaaluno_registro_id_fk" FOREIGN KEY ("registro_id") REFERENCES "escola_registroassiduidade" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
                        );
                        CREATE UNIQUE INDEX IF NOT EXISTS "escola_presencaaluno_registro_aluno"
                            ON "escola_presencaaluno" ("registro_id", "aluno_id");
                    """,
                    reverse_sql='DROP TABLE IF EXISTS "escola_presencaaluno"',
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name='PerfilTurma',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('papel', models.CharField(choices=[('lider', 'Líder'), ('vice', 'Vice-Líder')], max_length=10)),
                        ('aluno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_turma', to='escola.aluno')),
                        ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perfis', to='escola.turma')),
                    ],
                    options={
                        'verbose_name': 'Perfil de Turma',
                        'verbose_name_plural': 'Perfis de Turma',
                        'unique_together': {('turma', 'papel')},
                    },
                ),
                migrations.CreateModel(
                    name='RegistroAssiduidade',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('data', models.DateField(auto_now_add=True)),
                        ('observacao', models.TextField(blank=True)),
                        ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_feitos', to='escola.aluno')),
                        ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_assiduidade', to='escola.turma')),
                    ],
                    options={
                        'verbose_name': 'Registro de Assiduidade',
                        'verbose_name_plural': 'Registros de Assiduidade',
                        'ordering': ['-data'],
                    },
                ),
                migrations.CreateModel(
                    name='PresencaAluno',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('presente', models.BooleanField(default=True)),
                        ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presencas', to='escola.aluno')),
                        ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presencas', to='escola.registroassiduidade')),
                    ],
                    options={
                        'verbose_name': 'Presença',
                        'verbose_name_plural': 'Presenças',
                        'unique_together': {('registro', 'aluno')},
                    },
                ),
            ],
        ),
    ]
