import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0004_merge'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                    CREATE TABLE IF NOT EXISTS "escola_perfilturma" (
                        "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        "papel" varchar(10) NOT NULL,
                        "aluno_id" integer NOT NULL UNIQUE REFERENCES "escola_aluno" ("user_id") DEFERRABLE INITIALLY DEFERRED,
                        "turma_id" bigint NOT NULL REFERENCES "escola_turma" ("id") DEFERRABLE INITIALLY DEFERRED,
                        CONSTRAINT "escola_perfilturma_turma_id_papel_uniq" UNIQUE ("turma_id", "papel")
                    );
                    CREATE INDEX IF NOT EXISTS "escola_perfilturma_turma_id_idx" ON "escola_perfilturma" ("turma_id");

                    CREATE TABLE IF NOT EXISTS "escola_registroassiduidade" (
                        "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        "data" date NOT NULL,
                        "observacao" text NOT NULL,
                        "registrado_por_id" integer NOT NULL REFERENCES "escola_aluno" ("user_id") DEFERRABLE INITIALLY DEFERRED,
                        "turma_id" bigint NOT NULL REFERENCES "escola_turma" ("id") DEFERRABLE INITIALLY DEFERRED
                    );
                    CREATE INDEX IF NOT EXISTS "escola_registroassiduidade_registrado_por_id_idx" ON "escola_registroassiduidade" ("registrado_por_id");
                    CREATE INDEX IF NOT EXISTS "escola_registroassiduidade_turma_id_idx" ON "escola_registroassiduidade" ("turma_id");

                    CREATE TABLE IF NOT EXISTS "escola_presencaaluno" (
                        "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        "presente" boolean NOT NULL,
                        "aluno_id" integer NOT NULL REFERENCES "escola_aluno" ("user_id") DEFERRABLE INITIALLY DEFERRED,
                        "registro_id" bigint NOT NULL REFERENCES "escola_registroassiduidade" ("id") DEFERRABLE INITIALLY DEFERRED,
                        CONSTRAINT "escola_presencaaluno_registro_id_aluno_id_uniq" UNIQUE ("registro_id", "aluno_id")
                    );
                    CREATE INDEX IF NOT EXISTS "escola_presencaaluno_aluno_id_idx" ON "escola_presencaaluno" ("aluno_id");
                    CREATE INDEX IF NOT EXISTS "escola_presencaaluno_registro_id_idx" ON "escola_presencaaluno" ("registro_id");
                    """,
                    reverse_sql="""
                    DROP TABLE IF EXISTS "escola_presencaaluno";
                    DROP TABLE IF EXISTS "escola_registroassiduidade";
                    DROP TABLE IF EXISTS "escola_perfilturma";
                    """,
                )
            ],
            state_operations=[
                migrations.CreateModel(
                    name='PerfilTurma',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('papel', models.CharField(choices=[('lider', 'LÃ­der'), ('vice', 'Vice-LÃ­der')], max_length=10)),
                        ('aluno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_turma', to='escola.aluno')),
                        ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perfis', to='escola.turma')),
                    ],
                    options={
                        'verbose_name': 'Perfil de Turma',
                        'verbose_name_plural': 'Perfis de Turma',
                        'unique_together': {('turma', 'papel')},
                    },
                ),
                migrations.CreateModel(
                    name='RegistroAssiduidade',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('data', models.DateField(auto_now_add=True)),
                        ('observacao', models.TextField(blank=True)),
                        ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_feitos', to='escola.aluno')),
                        ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_assiduidade', to='escola.turma')),
                    ],
                    options={
                        'verbose_name': 'Registro de Assiduidade',
                        'verbose_name_plural': 'Registros de Assiduidade',
                        'ordering': ['-data'],
                    },
                ),
                migrations.CreateModel(
                    name='PresencaAluno',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('presente', models.BooleanField(default=True)),
                        ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presencas', to='escola.aluno')),
                        ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presencas', to='escola.registroassiduidade')),
                    ],
                    options={
                        'verbose_name': 'PresenÃ§a',
                        'verbose_name_plural': 'PresenÃ§as',
                        'unique_together': {('registro', 'aluno')},
                    },
                ),
            ],
        ),
    ]
