# Generated by Django 5.2.7 on 2026-04-30 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0005_add_assiduidade_models'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='presencaaluno',
            options={'verbose_name': 'Presença', 'verbose_name_plural': 'Presenças'},
        ),
        migrations.AlterField(
            model_name='perfilturma',
            name='papel',
            field=models.CharField(choices=[('lider', 'Líder'), ('vice', 'Vice-Líder')], max_length=10),
        ),
    ]
