# Generated by Django 5.2.7 on 2026-05-15 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0011_provaindividual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materia',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='SimuladoQuestao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulado_questoes', to='escola.questao')),
                ('simulado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulado_questoes', to='escola.simulado')),
            ],
            options={
                'verbose_name': 'Questão do Simulado',
                'verbose_name_plural': 'Questões do Simulado',
                'unique_together': {('simulado', 'questao')},
            },
        ),
        migrations.AlterField(
            model_name='simulado',
            name='questoes',
            field=models.ManyToManyField(related_name='simulados', through='escola.SimuladoQuestao', to='escola.questao'),
        ),
    ]
