# Generated by Django 5.2.7 on 2026-06-30 13:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("escola", "0013_avaliacao_decimal_questao_imagem"),
    ]

    operations = [
        migrations.AddField(
            model_name="simulado",
            name="area",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PRT", "Português"),
                    ("MTM", "Matemática"),
                    ("LING", "Linguagens e Códigos"),
                    ("HUM", "Ciências Humanas"),
                    ("NAT", "Ciências da Natureza"),
                ],
                default="",
                max_length=4,
            ),
        ),
        migrations.AddField(
            model_name="simulado",
            name="av_tipo",
            field=models.CharField(
                blank=True,
                choices=[("AV1", "AV1"), ("AV2", "AV2"), ("AV3", "AV3 (Qualitativa)")],
                default="",
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="simulado",
            name="epoca",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1B", "1° Bimestre"),
                    ("2B", "2° Bimestre"),
                    ("3B", "3° Bimestre"),
                    ("4B", "4° Bimestre"),
                ],
                default="",
                max_length=2,
            ),
        ),
        migrations.CreateModel(
            name="ResultadoSimulado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("iniciado_em", models.DateTimeField(auto_now_add=True)),
                ("enviado_em", models.DateTimeField(blank=True, null=True)),
                (
                    "nota",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=4,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendente_correcao", "Pendente de correção"),
                            ("corrigido", "Corrigido"),
                        ],
                        default="pendente_correcao",
                        max_length=20,
                    ),
                ),
                ("cancelado", models.BooleanField(default=False)),
                (
                    "aluno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resultados_simulado",
                        to="escola.aluno",
                    ),
                ),
                (
                    "simulado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resultados",
                        to="escola.simulado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Resultado de Simulado",
                "verbose_name_plural": "Resultados de Simulado",
                "ordering": ["-iniciado_em"],
                "unique_together": {("simulado", "aluno")},
            },
        ),
        migrations.CreateModel(
            name="NotaQualitativa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "epoca",
                    models.CharField(
                        choices=[
                            ("1B", "1° Bimestre"),
                            ("2B", "2° Bimestre"),
                            ("3B", "3° Bimestre"),
                            ("4B", "4° Bimestre"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "nota",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "aluno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notas_qualitativas",
                        to="escola.aluno",
                    ),
                ),
                (
                    "materia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notas_qualitativas",
                        to="escola.materia",
                    ),
                ),
                (
                    "professor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notas_qualitativas_dadas",
                        to="escola.professor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nota Qualitativa",
                "verbose_name_plural": "Notas Qualitativas",
                "ordering": ["epoca", "materia"],
                "unique_together": {("aluno", "epoca", "materia")},
            },
        ),
        migrations.CreateModel(
            name="RespostaAluno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("texto", models.TextField(blank=True, default="")),
                ("correta", models.BooleanField(blank=True, null=True)),
                (
                    "pontos",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "alternativa",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="respostas",
                        to="escola.alternativaquestao",
                    ),
                ),
                (
                    "questao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="respostas_aluno",
                        to="escola.questao",
                    ),
                ),
                (
                    "resultado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="respostas",
                        to="escola.resultadosimulado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Resposta do Aluno",
                "verbose_name_plural": "Respostas do Aluno",
                "unique_together": {("resultado", "questao")},
            },
        ),
        migrations.CreateModel(
            name="NotaArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "epoca",
                    models.CharField(
                        choices=[
                            ("1B", "1° Bimestre"),
                            ("2B", "2° Bimestre"),
                            ("3B", "3° Bimestre"),
                            ("4B", "4° Bimestre"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "av_tipo",
                    models.CharField(
                        choices=[
                            ("AV1", "AV1"),
                            ("AV2", "AV2"),
                            ("AV3", "AV3 (Qualitativa)"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "area",
                    models.CharField(
                        choices=[
                            ("PRT", "Português"),
                            ("MTM", "Matemática"),
                            ("LING", "Linguagens e Códigos"),
                            ("HUM", "Ciências Humanas"),
                            ("NAT", "Ciências da Natureza"),
                        ],
                        max_length=4,
                    ),
                ),
                (
                    "nota",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "origem",
                    models.CharField(
                        choices=[("auto", "Automática"), ("manual", "Manual")],
                        default="auto",
                        max_length=6,
                    ),
                ),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "aluno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notas_area",
                        to="escola.aluno",
                    ),
                ),
                (
                    "resultado",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notas_geradas",
                        to="escola.resultadosimulado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nota por Área",
                "verbose_name_plural": "Notas por Área",
                "ordering": ["epoca", "av_tipo", "area"],
                "unique_together": {("aluno", "epoca", "av_tipo", "area")},
            },
        ),
    ]
