# Generated by Django 5.2.7 on 2026-07-01 21:11

from django.db import migrations

from escola.grade_config import DISCIPLINAS


def seed_disciplinas(apps, schema_editor):
    Materia = apps.get_model("escola", "Materia")
    for sigla, nome in DISCIPLINAS:
        Materia.objects.get_or_create(sigla=sigla, defaults={"nome": nome})


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("escola", "0014_simulado_area_simulado_av_tipo_simulado_epoca_and_more"),
    ]

    operations = [
        migrations.RunPython(seed_disciplinas, noop),
    ]
