# Generated by Django 5.2.7 on 2026-07-07 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("escola", "0015_seed_disciplinas"),
    ]

    operations = [
        migrations.AddField(
            model_name="alternativaquestao",
            name="imagem",
            field=models.ImageField(
                blank=True, null=True, upload_to="alternativas_imagens/"
            ),
        ),
        migrations.AlterField(
            model_name="alternativaquestao",
            name="texto",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
    ]
