# Generated by Django 5.2.7 on 2026-07-27 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("escola", "0018_logatividade"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ProvaIndividual",
        ),
    ]
