# Generated by Django 5.2.7 on 2026-07-29 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("escola", "0019_delete_provaindividual"),
    ]

    operations = [
        migrations.AddField(
            model_name="aluno",
            name="cpf",
            field=models.CharField(blank=True, max_length=14, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="aluno",
            name="nome_mae",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="aluno",
            name="telefone",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
    ]
