# Generated by Django 5.2.7 on 2026-08-03 11:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("escola", "0021_remove_aluno_matricula_aluno_data_nascimento_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Aviso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("matricula", "Matrícula"),
                            ("evento", "Evento"),
                            ("esporte", "Esporte"),
                            ("biblioteca", "Biblioteca"),
                        ],
                        default="evento",
                        max_length=20,
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=220, unique=True)),
                ("descricao_curta", models.CharField(max_length=300)),
                ("imagem_capa", models.ImageField(upload_to="avisos/capas/")),
                (
                    "imagem_capa_alt",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "conteudo",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="HTML gerado pelo editor rico do admin, com imagens embutidas.",
                    ),
                ),
                (
                    "publicar_em",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "ativo",
                    models.BooleanField(
                        default=False,
                        help_text="Só aparece no mural público quando marcado (publicado).",
                    ),
                ),
                ("ordem", models.IntegerField(default=0)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "autor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="avisos_criados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Aviso do Mural",
                "verbose_name_plural": "Avisos do Mural",
                "ordering": ["ordem", "-publicar_em"],
            },
        ),
    ]
